/*
 * This code emulates the noise generated by most 315/434MHz
 * receivers while the transmitter is off or out of range,
 * so you can use this example to tune the servocto's noise
 * filter.
 * 
 * Written by Daniel Sitrakiniaina Razafimaharavo
 */
void setup() {
  pinMode(9, OUTPUT);
}

void loop() {
  //Create a signal with random frequency and duty cycle
  digitalWrite(9, HIGH);
  delayMicroseconds(random(1000,5000)); 
  digitalWrite(9, LOW); 
  delayMicroseconds(random(1100,4900));       
}
